FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy requirements and install dependencies (if any)
# COPY requirements.txt .
# RUN pip install -r requirements.txt

# Copy application code
COPY . .

# Set default command (update as needed)
CMD ["python", "main.py"]
# docker build --platform linux/amd64 -t pdfextractor_challenge1a:20250728 .

